// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjiU_hWQJ7ZPovllCLIfqINjjUuZzbUaQ',
    appId: '1:824606719749:android:b81b486ab37b537557816c',
    messagingSenderId: '824606719749',
    projectId: 'ghiles-flutter-fire-tp',
    storageBucket: 'ghiles-flutter-fire-tp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeodf6GAdqzkWeCft_FEFosGpIeILyT9g',
    appId: '1:824606719749:ios:e82f9a9a5b84ec5f57816c',
    messagingSenderId: '824606719749',
    projectId: 'ghiles-flutter-fire-tp',
    storageBucket: 'ghiles-flutter-fire-tp.appspot.com',
    iosClientId: '824606719749-0d25poqbuvh5h9i0mi7rkm4hh87sndnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghilesFlutterFireTp',
  );
}
